[workspace]
members = [
    "crates/parser",
    "crates/interpreter",
    "crates/mk_run", 
    "crates/compiler",
]

[alias]
mk_run = "run -p mk_run"
mk_repl = "run -p mk_run -- --reple"
mk_parse = "run -p mk_run -- --repl"
mk_comp = "run -p mk_run -- --replc"
